### PR TITLE
Add new post on authentication

### PR DESCRIPTION
**Pull request by amandeepmittal**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by harrysolovay** [comment]
@amandeepmittal can you please wrap your `description` with double quotes instead of single quotes? This will fix the parse error that's currently breaking the build.

**Comment by amandeepmittal** [comment]
@harrysolovay Done. 👍

**Comment by swaminator** [comment]
@amandeepmittal can you please update your repo? We added circleci tests and it doesn't seem like your forked repo has the config.

**Comment by amandeepmittal** [comment]
@swaminator I have re-forked the repo. Should I submit a new PR?

**Comment by swaminator** [comment]
@amandeepmittal no worries! we already merged your PR. You can find your post here: https://amplify.aws/community/contributors/aman-mittal

Thanks for the awesome contributions! Please email aws-amplify-customer@amazon.com with your home address. We'd love to send some Amplify swag your way!

**Comment by amandeepmittal** [comment]
@swaminator WOW! Thanks a lot :)

Yes, I will email you and thanks in advance for the swag 👍

**Pull request closed without merging**
