### PR TITLE
👌 IMPROVE: Contributor Styles

### PR DESCRIPTION
**Pull request by ahmadawais**
The contributors page has unlimited width available for the description. Anything beyond 600px wide is super hard to read. Moreover, the social icons look far to apart.

This PR fixes that.

## AFTER ↓

Peace! ✌️

### CODE REVIEW

**Comment by harrysolovay** [comment]
Hi @ahmadawais –– can you please remove the social-link related styles? Otherwise, nice stylistic catch 💯

**Comment by ahmadawais** [comment]
@harrysolovay The social media icons look pretty weird that far apart. I can remove it of course but I'd ask you to reconsider. :)

**Comment by harrysolovay** [comment]
I agree, but your proposed implementation causes problems in certain cases. Any spot on the contributor card should be clickable (as the hover style suggests). When a contributor card takes up less horizontal space, the space-around style looks better. I think the right solution is to create another contributor card for the expanded view. Given this PR is out of sync (as we pushed updates yesterday), I’ll work on adding the changes in today. Thank you again for calling attention to this.

**Comment by ahmadawais** [comment]
I had already fixed the merge issues 🤔

**Pull request closed without merging**
