### PR TITLE
New Multi-Auth Article for AppSync

### PR DESCRIPTION
**Pull request by awsed**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by harrysolovay** [comment]
Hi @awsed –– the Platform `Generic/Backend` doesn't currently exist. I'm wondering if you think this is a good addition to the platform list? Or if there's a better label? `Backend` sounds a little better to me personally.

There's also the question of whether every other post should then have the `Backend` label (because they all involve using Amplify, which is a Backend tool). Is there a better platform label for this post?

**Comment by awsed** [comment]
Hi @harrysolovay, agree `Backend` sounds better. I just added something as there was no option. If you want to be more specific, you could just use `AppSync` or `GraphQL` instead as basically it's an AppSync related article.

**Comment by harrysolovay** [comment]
@awsed great! Then let's label it as "API (GraphQL)".

One last thing: the max description length is 500 characters. It's currently at 536. Any chance you could please shave off a few?

**Comment by awsed** [comment]
We can remove the last sentence so it's "If you’re using GraphQL, wouldn’t it be great if you could easily define different authorization modes for you application data at the type, field or operation level directly in your schema instead of having a single global authorization mode for an API? What if you could have different types of authorization providers for different parts of your schema?". Do you want me to submit another PR?

**Comment by harrysolovay** [comment]
@awsed nope. I got it from here 👍

**Pull request merged**
